# Generated by Django 4.2 on 2023-07-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Новая запись!', max_length=255, verbose_name='Заголовок'),
        ),
    ]
