# Generated by Django 4.2 on 2023-08-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_b', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
