# Generated by Django 4.2 on 2023-08-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_b', '0003_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default=1, upload_to='online_shop_b/', verbose_name='изображения'),
            preserve_default=False,
        ),
    ]
